<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Mahasiswa extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Mahasiswa_model');
    } 

    /*
     * Listing of mahasiswa
     */
    function index()
    {
        $data['mahasiswa'] = $this->Mahasiswa_model->get_all_mahasiswa();
        
        $data['_view'] = 'Mahasiswa/index';
        
        $this->load->view('templates/header',$data);
        $this->load->view('templates/sidebar',$data);
       $this->load->view('layouts/main',$data);
        $this->load->view('templates/footer');
        
    }

    /*
     * Adding a new mahasiswa
     */
    function add()
    {  

        $data['_view'] = 'Mahasiswa/Tambah_data';
        $this->load->view('templates/header',$data);
        $this->load->view('templates/sidebar',$data);
       $this->load->view('mahasiswa/add');
        $this->load->view('templates/footer');


        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nama' => $this->input->post('nama'),
				'kelas' => $this->input->post('kelas'),
                'nim' => $this->input->post('nim'),
            );
            
            $mahasiswa_id = $this->Mahasiswa_model->add_mahasiswa($params);
            redirect('mahasiswa/index');
        }
        else
        {            
            $data['_view'] = 'mahasiswa/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a mahasiswa
     */
    function edit($nim)
    { 
        $data['_view'] = 'Mahasiswa/Edit_data';
        // check if the mahasiswa exists before trying to edit it
        $data['mahasiswa'] = $this->Mahasiswa_model->get_mahasiswa($nim);

        
        $this->load->view('templates/header',$data);
        $this->load->view('templates/sidebar',$data);
       $this->load->view('mahasiswa/edit');
        $this->load->view('templates/footer');

        
        if(isset($data['mahasiswa']['nim']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nama' => $this->input->post('nama'),
					'kelas' => $this->input->post('kelas'),
                    'nim' => $this->input->post('nim'),
                );

                $this->Mahasiswa_model->update_mahasiswa($nim,$params);            
                redirect('mahasiswa/index');
            }
            else
            {
                $data['_view'] = 'mahasiswa/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The mahasiswa you are trying to edit does not exist.');
    } 

    /*
     * Deleting mahasiswa
     */
    function remove($nim)
    {
        $mahasiswa = $this->Mahasiswa_model->get_mahasiswa($nim);

        // check if the mahasiswa exists before trying to delete it
        if(isset($mahasiswa['nim']))
        {
            $this->Mahasiswa_model->delete_mahasiswa($nim);
            redirect('mahasiswa/index');
        }
        else
            show_error('The mahasiswa you are trying to delete does not exist.');
    }
    
}
