<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Matakuliah extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Matakuliah_model');
    } 

    /*
     * Listing of matakuliah
     */
    function index()
    {
        $data['matakuliah'] = $this->Matakuliah_model->get_all_matakuliah();
        
        $data['_view'] = 'matakuliah/index';
       
        $this->load->view('templates/header',$data);
        $this->load->view('templates/sidebar',$data);
         $this->load->view('layouts/main',$data);
        $this->load->view('templates/footer');
     
    }

    /*
     * Adding a new matakuliah
     */
    function add()
    {   
        $data['_view'] = 'matakuliah/Tambah_data';
       
        $this->load->view('templates/header',$data);
        $this->load->view('templates/sidebar',$data);
         $this->load->view('matakuliah/add');
        $this->load->view('templates/footer');
     
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'mata_kuliah' => $this->input->post('mata_kuliah'),
				'sks' => $this->input->post('sks'),
                'kode' => $this->input->post('kode')
            );
            
            $matakuliah_id = $this->Matakuliah_model->add_matakuliah($params);
            redirect('matakuliah/index');
        }
        else
        {            
            $data['_view'] = 'matakuliah/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a matakuliah
     */
    function edit($kode)
    {   
         $data['_view'] = 'matakuliah/Edit_data';
        // check if the matakuliah exists before trying to edit it
        $data['matakuliah'] = $this->Matakuliah_model->get_matakuliah($kode);

        $this->load->view('templates/header',$data);
        $this->load->view('templates/sidebar',$data);
         $this->load->view('matakuliah/edit');
        $this->load->view('templates/footer');

        if(isset($data['matakuliah']['kode']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'mata_kuliah' => $this->input->post('mata_kuliah'),
					'sks' => $this->input->post('sks'),
                    'kode' => $this->input->post('kode')
                );

                $this->Matakuliah_model->update_matakuliah($kode,$params);            
                redirect('matakuliah/index');
            }
            else
            {
                $data['_view'] = 'matakuliah/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The matakuliah you are trying to edit does not exist.');
    } 

    /*
     * Deleting matakuliah
     */
    function remove($kode)
    {
        $matakuliah = $this->Matakuliah_model->get_matakuliah($kode);

        // check if the matakuliah exists before trying to delete it
        if(isset($matakuliah['kode']))
        {
            $this->Matakuliah_model->delete_matakuliah($kode);
            redirect('matakuliah/index');
        }
        else
            show_error('The matakuliah you are trying to delete does not exist.');
    }
    
}
