<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Dosen_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get dosen by nidn
     */
    function get_dosen($nidn)
    {
        return $this->db->get_where('dosen',array('nidn'=>$nidn))->row_array();
    }
        
    /*
     * Get all dosen
     */
    function get_all_dosen()
    {
        $this->db->order_by('nidn', 'desc');
        return $this->db->get('dosen')->result_array();
    }
        
    /*
     * function to add new dosen
     */
    function add_dosen($params)
    {
        $this->db->insert('dosen',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update dosen
     */
    function update_dosen($nidn,$params)
    {
        $this->db->where('nidn',$nidn);
        return $this->db->update('dosen',$params);
    }
    
    /*
     * function to delete dosen
     */
    function delete_dosen($nidn)
    {
        return $this->db->delete('dosen',array('nidn'=>$nidn));
    }
}
