<?php
/* 
 * Generated by CRUDigniter v3.4 
 * www.crudigniter.com
 */
 
class Matakuliah_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get matakuliah by kode
     */
    function get_matakuliah($kode)
    {
        return $this->db->get_where('matakuliah',array('kode'=>$kode))->row_array();
    }
        
    /*
     * Get all matakuliah
     */
    function get_all_matakuliah()
    {
        $this->db->order_by('kode','desc');
        return $this->db->get('matakuliah')->result_array();
    }
        
    /*
     * function to add new matakuliah
     */
    function add_matakuliah($params)
    {
        $this->db->insert('matakuliah',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update matakuliah
     */
    function update_matakuliah($kode,$params)
    {
        $this->db->where('kode',$kode);
        return $this->db->update('matakuliah',$params);
    }
    
    /*
     * function to delete matakuliah
     */
    function delete_matakuliah($kode)
    {
        return $this->db->delete('matakuliah',array('kode'=>$kode));
    }
}
